project:
  type: "website"


website:
  title: "QGreenland-Net"
  site-url: "https://qgreenland-net.github.io"
  repo-url: &repo-url "https://github.com/qgreenland-net/qgreenland-net.github.io"
  repo-actions: ["edit", "issue"]


  navbar:
    left:
      - text: "Records"
        menu:
        - text: "Decisions"
          href: "decisions/index.md"
        - text: "Notes"
          href: "notes/index.md"
      - text: "Media"
        menu:
        - text: "Diagrams"
          href: "diagrams/index.md"
        - text: "Interfaces"
          href: "interfaces/index.md"
        - text: "Presentations"
          href: "presentations/index.md"
      - text: "Requirements"
        href: "requirements.md"
      - text: "Evaluations"
        href: "evaluations/index.md"
      - text: "How-tos"
        href: "how-tos/index.md"

    right:
      - icon: "github"
        aria-label: "GitHub"
        href: *repo-url


  page-footer:
    left: "© NSIDC and ADC 2024"
    right: "Built with [Quarto](https://quarto.org/) ❤️"


format:
  html:
    theme:
      light: ["flatly", "styles.css"]
      dark: ["darkly", "styles.css"]
    toc: true
