project:
  type: "website"


website:
  title: "QGreenland-Net"
  site-url: "https://qgreenland-net.github.io"
  repo-url: &repo-url "https://github.com/qgreenland-net/qgreenland-net.github.io"
  repo-actions: ["edit", "issue"]


  navbar:
    left:
      - text: "Contributors"
        href: "contributing/index.md"
      - text: "Workshops"
        href: "workshops/index.md"


    right:
      - icon: "github"
        aria-label: "GitHub"
        href: *repo-url

  sidebar:
    - title: "Contributors"
      contents:
        - decisions/index.md
        - notes/index.md
        - diagrams/index.md
        - interfaces/index.md
        - presentations/index.md
        - evaluations/index.md
        - requirements.md
        - how-tos/index.md
        - contributing/index.md

  page-footer:
    left: "© NSIDC and ADC 2024"
    right: "Built with [Quarto](https://quarto.org/) ❤️"


format:
  html:
    theme:
      light: ["flatly", "styles.css"]
      dark: ["darkly", "styles.css"]
    toc: true
