project:
  type: "website"

website:
  title: "QGreenland-Net"
  navbar:
    left:
      - text: "Home"
        href: "index.md"
      - text: "Decision records"
        href: "decisions/index.md"
      - text: "Notes"
        href: "notes/index.md"
      - text: "Diagrams"
        href: "diagrams/index.md"

format:
  html:
    theme: "cosmo"
    css: "styles.css"
    toc: true
