project:
  type: "website"


website:
  title: "QGreenland-Net"
  site-url: "https://qgreenland-net.github.io"
  repo-url: &repo-url "https://github.com/qgreenland-net/qgreenland-net.github.io"
  repo-actions: ["edit", "issue"]


  navbar:
    left:
      - text: "Decision records"
        href: "decisions/index.md"
      - text: "Notes"
        href: "notes/index.md"
      - text: "Diagrams"
        href: "diagrams/index.md"
      - text: "Presentations"
        href: "presentations/index.md"

    right:
      - icon: "github"
        aria-label: "GitHub"
        href: *repo-url


  page-footer:
    left: "© NSIDC and ADC 2024"
    right: "Built with [Quarto](https://quarto.org/) ❤️"


format:
  html:
    theme:
      light: ["flatly", "styles.css"]
      dark: ["darkly", "styles.css"]
    toc: true
