project:
  type: "website"

website:
  title: "QGreenland-Net"
  site-url: "https://qgreenland-net.github.io"
  repo-url: &repo-url "https://github.com/qgreenland-net/qgreenland-net.github.io"
  repo-actions: ["edit", "issue"]


  navbar:
    left:
      - text: "Home"
        href: "index.md"
      - text: "Decision records"
        href: "decisions/index.md"
      - text: "Notes"
        href: "notes/index.md"
      - text: "Diagrams"
        href: "diagrams/index.md"

    right:
      - icon: "github"
        aria-label: "GitHub"
        href: *repo-url


format:
  html:
    theme: "cosmo"
    css: "styles.css"
    toc: true
